<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MonthlyDirectDebit</name>
   <tag></tag>
   <elementGuidId>d9ec4781-ef88-48ea-96df-f4d2b1f350da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>div.label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>div.label</value>
   </webElementProperties>
</WebElementEntity>
