<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectDirectDebitModalContentText</name>
   <tag></tag>
   <elementGuidId>f5bc33be-8c89-47b8-ba98-55460b5f0911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#modal-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#modal-body</value>
   </webElementProperties>
</WebElementEntity>
