<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InlineErrorText</name>
   <tag></tag>
   <elementGuidId>e63b170f-8e62-4b7d-b5d3-fa3c6f60baef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>span.field-validation-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>span.field-validation-error</value>
   </webElementProperties>
</WebElementEntity>
