<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YesContentText</name>
   <tag></tag>
   <elementGuidId>97d8871f-4d77-4a22-89c7-76706267a3d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
</WebElementEntity>
