<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YesRadioButton</name>
   <tag></tag>
   <elementGuidId>333f61cf-54fb-4d56-af8e-98c86b164e74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>div.label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>div.label</value>
   </webElementProperties>
</WebElementEntity>
