<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GenericFalloutContentText</name>
   <tag></tag>
   <elementGuidId>04ef3ccb-6719-46d6-9a29-5a3c5e3126af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>section.main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>section.main</value>
   </webElementProperties>
</WebElementEntity>
