<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LandlineTextBox</name>
   <tag></tag>
   <elementGuidId>948289c6-4727-4c00-94d7-0cf9b1d19635</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>input#Landline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>input#Landline</value>
   </webElementProperties>
</WebElementEntity>
