<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LandlineTextBoxLabel</name>
   <tag></tag>
   <elementGuidId>1f6f7519-7e10-41dd-bf6e-266ef320ca1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='enter-postcode-form']//label[@for='Landline']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='enter-postcode-form']//label[@for='Landline']</value>
   </webElementProperties>
</WebElementEntity>
