<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LineCheckerLandLineValidationMessageText</name>
   <tag></tag>
   <elementGuidId>80c8b38d-81d0-459a-8ec1-811f5a90cfc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#Landline-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#Landline-error</value>
   </webElementProperties>
</WebElementEntity>
