<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ParagraphThreeText</name>
   <tag></tag>
   <elementGuidId>0efafba5-b886-4e56-957f-2a27292010e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>ParagraphThreeText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>ParagraphThreeText</value>
   </webElementProperties>
</WebElementEntity>
