<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PostCodeTextBox</name>
   <tag></tag>
   <elementGuidId>59a850be-eebc-47d0-ad9c-39f6c2e2b467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#PostCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#PostCode</value>
   </webElementProperties>
</WebElementEntity>
