<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PostCodePageHeaderText</name>
   <tag></tag>
   <elementGuidId>ab5a0b67-cc7c-4418-b7db-24ea245cabfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>label.form-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>label.form-label</value>
   </webElementProperties>
</WebElementEntity>
