<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PostCodeValidationMessageText</name>
   <tag></tag>
   <elementGuidId>0be0b866-381d-4ba1-8902-3099af657a6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#PostCode-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#PostCode-error</value>
   </webElementProperties>
</WebElementEntity>
