<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConfirmAddressNextButton</name>
   <tag></tag>
   <elementGuidId>d72c62ef-8fa7-48d8-a647-20e76f367127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#button-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#button-submit</value>
   </webElementProperties>
</WebElementEntity>
