<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectAddressContentText</name>
   <tag></tag>
   <elementGuidId>fc633300-e1e8-4cd8-818b-4b1e1c2289e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>section.main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>section.main</value>
   </webElementProperties>
</WebElementEntity>
