<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SelectAddressDropdown</name>
   <tag></tag>
   <elementGuidId>7995d22d-26c3-48e0-998d-2bff9288e62b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SelectedAddressId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SelectedAddressId</value>
   </webElementProperties>
</WebElementEntity>
