<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnergyUsagePageIDontKnowMyUsage</name>
   <tag></tag>
   <elementGuidId>2983262f-6cfd-4475-b8b9-7b9fd287eca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;&quot;myTab&quot;&quot;]/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;&quot;myTab&quot;&quot;]/li[2]</value>
   </webElementProperties>
</WebElementEntity>
