<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>InlineErrorText</name>
   <tag></tag>
   <elementGuidId>77ab0bbd-e991-49da-bdc4-c51d6cd303b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>InlineErrorText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>InlineErrorText</value>
   </webElementProperties>
</WebElementEntity>
