<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StandardMeter</name>
   <tag></tag>
   <elementGuidId>881bd6fc-d7f1-4d8a-b363-c5f016495e8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>div.label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>div.label</value>
   </webElementProperties>
</WebElementEntity>
