<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BundlesImportantInformationText</name>
   <tag></tag>
   <elementGuidId>193f5936-fc2d-42ce-98d1-ed9796d92250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>BundlesImportantInformationText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>BundlesImportantInformationText</value>
   </webElementProperties>
</WebElementEntity>
