<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnergyImportantInformationText</name>
   <tag></tag>
   <elementGuidId>856a84f3-2187-4374-b78a-ea7cc7fd3687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#important-information-energy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#important-information-energy</value>
   </webElementProperties>
</WebElementEntity>
