<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TilInfoText</name>
   <tag></tag>
   <elementGuidId>8c0f8f34-1dd1-4fee-894d-425061c18fe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.modal-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.modal-body</value>
   </webElementProperties>
</WebElementEntity>
