<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AreYouAnSseCustomerParagraphText</name>
   <tag></tag>
   <elementGuidId>808b8bac-e99b-4848-ae02-8a0b54a1acf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
</WebElementEntity>
