<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SseCustomerOptionPageHeadingText</name>
   <tag></tag>
   <elementGuidId>a8a772a2-9be3-4403-bbc8-46129e797907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>h1</value>
   </webElementProperties>
</WebElementEntity>
