<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitPageAccountHolderField</name>
   <tag></tag>
   <elementGuidId>e77648f0-5724-4f73-bfd4-52d0e019ed6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#AccountHolder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#AccountHolder</value>
   </webElementProperties>
</WebElementEntity>
