<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitPageAgreementText</name>
   <tag></tag>
   <elementGuidId>c6d1a0d5-0b93-460a-86cb-7009742bc044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#checkbox-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#checkbox-label</value>
   </webElementProperties>
</WebElementEntity>
