<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitPageSortCodeInputFieldTwo</name>
   <tag></tag>
   <elementGuidId>9e65f444-6498-416f-8305-46c5eb84076c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SortCodeSegmentTwo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SortCodeSegmentTwo</value>
   </webElementProperties>
</WebElementEntity>
