<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitPageSortCodeInputFieldThree</name>
   <tag></tag>
   <elementGuidId>87efb5bf-737c-4ed4-bab1-67a2f4d7011d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#SortCodeSegmentThree</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#SortCodeSegmentThree</value>
   </webElementProperties>
</WebElementEntity>
