<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitOkNextButton</name>
   <tag></tag>
   <elementGuidId>00e48695-00e0-4af5-b06e-e2747b8ef5f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#btnSubmitAccountDetails</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#btnSubmitAccountDetails</value>
   </webElementProperties>
</WebElementEntity>
