<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitAccountHolderNameErrorText</name>
   <tag></tag>
   <elementGuidId>a12e92c7-6d14-40bd-97a7-0b8a391dc8e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#AccountHolder-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#AccountHolder-error</value>
   </webElementProperties>
</WebElementEntity>
