<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitPageAccountNumberInputField</name>
   <tag></tag>
   <elementGuidId>111fe8ce-51d0-4248-bfa7-27a2a49048ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#AccountNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#AccountNumber</value>
   </webElementProperties>
</WebElementEntity>
