<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitAgreementErrorText</name>
   <tag></tag>
   <elementGuidId>07c80352-d40d-481c-ab08-a3fcbf68507e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#IsAuthorisedChecked-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#IsAuthorisedChecked-error</value>
   </webElementProperties>
</WebElementEntity>
