<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitAccountNumberErrorText</name>
   <tag></tag>
   <elementGuidId>a0eed921-f159-4f74-82bf-95ea5d1b4536</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#AccountNumber-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#AccountNumber-error</value>
   </webElementProperties>
</WebElementEntity>
