<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitSortCodeErrorText</name>
   <tag></tag>
   <elementGuidId>0b49c284-2846-40da-8e6a-1061d87a098f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>DirectDebitSortCodeErrorText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>DirectDebitSortCodeErrorText</value>
   </webElementProperties>
</WebElementEntity>
