<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DirectDebitPagePaymentDateInputField</name>
   <tag></tag>
   <elementGuidId>5dcfa2ba-a292-4199-90d5-cf87508bfe0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#DirectDebitDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#DirectDebitDate</value>
   </webElementProperties>
</WebElementEntity>
