<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OnlineAccountContentText</name>
   <tag></tag>
   <elementGuidId>d0ed81b1-44b9-4548-a36b-2d2a887a36d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>section.main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>section.main</value>
   </webElementProperties>
</WebElementEntity>
