<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BackLinkButton</name>
   <tag></tag>
   <elementGuidId>dee3456a-d890-4330-b35c-ff0e8f995928</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#back-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#back-link</value>
   </webElementProperties>
</WebElementEntity>
