<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckYourDetailsContent</name>
   <tag></tag>
   <elementGuidId>720a24af-63b4-4697-ab9c-a7ee6c460761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#terms-and-conditions</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#terms-and-conditions</value>
   </webElementProperties>
</WebElementEntity>
