<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HeatingBreakdownTextContent</name>
   <tag></tag>
   <elementGuidId>4c44ff3c-2b48-4427-acd6-38308598a568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='home-services']//div[@class='col-xs-12']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='home-services']//div[@class='col-xs-12']</value>
   </webElementProperties>
</WebElementEntity>
