<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StepCounter</name>
   <tag></tag>
   <elementGuidId>75319a69-5ef9-4075-aaa1-f38c58b27f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>div.step-count</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>div.step-count</value>
   </webElementProperties>
</WebElementEntity>
