<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summaryPagecontent</name>
   <tag></tag>
   <elementGuidId>92de1d59-07f3-4bbb-b2a9-563d2c7f0314</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>section.main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>section.main</value>
   </webElementProperties>
</WebElementEntity>
