<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SummaryPageInfoTickBox</name>
   <tag></tag>
   <elementGuidId>286d406c-9923-4fe2-8c6e-e456ce481281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#checkbox-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#checkbox-label</value>
   </webElementProperties>
</WebElementEntity>
