<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SummaryPageConfirmOrder</name>
   <tag></tag>
   <elementGuidId>2b9ef695-6ceb-47b3-8b5f-cc53ed9f061c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#button-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#button-submit</value>
   </webElementProperties>
</WebElementEntity>
