<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WrongMeterDetailsLink</name>
   <tag></tag>
   <elementGuidId>d981ca03-8cf3-432d-8f1c-1c53afd065dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@data-target='#WrongMeterModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@data-target='#WrongMeterModal']</value>
   </webElementProperties>
</WebElementEntity>
