<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContactDetailsContentText</name>
   <tag></tag>
   <elementGuidId>d491b78a-06cc-4db9-9e63-0919a51671b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>section.main</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>section.main</value>
   </webElementProperties>
</WebElementEntity>
